### ISSUE TITLE
[sentry] generate SECRET_KEY in sentry.install

### ISSUE THREAD

**Issue by codekoala** [zancarius/archlinux-pkgbuilds#4]
I'm currently packaging up sentry for our local Arch repository at work (thanks again!). I don't anticipate sentry being deployed on many systems, but if that were to ever happen with a package built from this PKGBUILD, each system would have the same ``SECRET_KEY``.

Ideally, this would be generated on the fly in the ``post_install`` section of ``sentry.install``. I would submit another pull request, but I'm running low on time tonight. I can definitely get to this tomorrow and submit the pull request though.

**Comment by zancarius** [comment]
Hmm. I think I had it configured to do that at some point in the past but removed it for reasons I can't seem to remember. It *might* have been when I changed the PKGBUILD to pull all the dependencies from PyPI instead of, well, the nearly one-dozen packages that were almost nearly always either too new or too old for Sentry's tastes.

Tell you what. I'll make that change real quick and bump the pkgrel from the *repository's* copy. I suspect I won't upload that version to the AUR, however.

**Comment by codekoala** [comment]
That sounds great, thanks!

**Comment by zancarius** [comment]
Actually, this is probably something I should do ASAP since the size of the generated package is rather large (and it's more convenient and bandwidth friendly to use the package across multiple installs). I'll go ahead and upload the pkgrel bump regardless.

Thanks for catching this! Too often do I put together packages for my own purposes or curiosity, and either leave them neglected or overlook things other folks might prefer them to do.

Also, I greatly appreciate the pull requests--people love using the AUR comments but are a bit bashful about using Github even though it's *far* more convenient.

**Comment by codekoala** [comment]
Excellent, thank you!

I totally understand the whole AUR vs github thing. Comments are not very helpful for making progress compared to all that is github!

**Comment by zancarius** [comment]
Agreed!

I love the AUR, and its comments are often useful for a large number of reasons. Pasting major changes to a PKGBUILD or its kin... well, that's not one of them. ;)
