### ISSUE TITLE
Deprecated archey-omz-git

### ISSUE THREAD

**Issue by james-darkfox** [zancarius/archlinux-pkgbuilds#5]
Hello,

I'm unsure as to what happened to the repository, and I'm sorry to say that it had been deleted. Do you still use the old code?

Alternatively you might want to switch to: https://github.com/sorin-ionescu/prezto/

Cheers, James.

Edit: Generalized this message a bit.

**Comment by zancarius** [comment]
I switched to oh-my-zsh some time ago but left this in my repository, mostly because I'm just really forgetful. Sorry about that.

I'll go ahead and remove it. It'll give me a chance to clean things up a bit.

Thanks!

**Comment by james-darkfox** [comment]
Thanks. Also; according to nickserv. You haven't been on freenode in almost 3 years? You happen to use another name?

**Comment by zancarius** [comment]
Okay, I moved it to my `DEPRECATED` section, mostly because I didn't have the heart to remove it just yet. I need to go through those packages and (eventually?) decide what I want to keep.

To answer the comment you made earlier that for some reason isn't showing up here (edited?) but did appear via the Github mail: No, I haven't used Freenode in a long time. I probably have the password somewhere. I've never been much of an IRC junky, and after the weirdness Freenode had about a year or two ago I haven't had much interest returning.

Problem is that I can't decide if it's because I'm somewhat anti-social or lazy. It's like the joke: "I always used to be so undecided. Now I'm not so sure."

:)

**Comment by zancarius** [comment]
I'm going to close this for now. If you reaaaaaally want me to delete the package (or anything else you think might be too stale), feel free to continue commenting or make a new issue.

**Comment by james-darkfox** [comment]
Yes, was edited. I noticed after posting that the registered date was only 2 days before the last seen. :-P

IRC is great! However, for a decent channel you need a few things:

- People
- Decent topic for discussion such as a project
- Incentive to socialize (even if just for the discussion)

IRC is also the **MOST** reliable way to contact me. ;-) (Note: the email-alternative for freenode `/msg memoserv help`)

**Comment by james-darkfox** [comment]
archey-omz-git remains in the README. Also; yes, I would prefer that it were removed completely. Nothing that you need or can't recover via the magic that is git. Deprecated folders are quite messy in terms of git (you've deleted and created new objects). Deleting them doesn't purge them from git, so it is cleaner to just delete and recover from history if ever required.

**Comment by zancarius** [comment]
I used to use IRC with some varying degree of regularity *probably* some 15+ years ago (this might date me a bit). Mostly EFNET, and mostly because I used to enjoy 1) trackers (the music variety), 2) stupid IRC debates, and 3) instant messengers hadn't completely caught on (though they were growing). Not quite sure why I lost interest, but there's a reason in there somewhere. :)

Odd that the registered date was showing up then. IIRC, I actually used Freenode for a year or two. Maybe my recollection is off a bit, but I have a BitchX configuration file that dates back to a number of years ago, and I'm fairly sure I used it off and on for sometime thereafter.

**Comment by zancarius** [comment]
I'm aware of how git works. I use it regularly for my own projects. Don't be so naive as to assume a project structure was chosen due to ignorance over laziness. :)

There's a reason I created a deprecated folder, probably because I wanted to keep the packages in the working tree. I'm not quite sure why I didn't create a branch for that alone, but I suspect it had to do with some scripts I'd written for handling AUR-related cruft.

**Comment by james-darkfox** [comment]
Note for your DEPRECATED/README

"Do not expect the PKGBUILDs in this repo to persist for any length of time. They may be removed permanently for any reason." As I mentioned above, this is not the case. :-)

**Comment by james-darkfox** [comment]
Fair enough. Personally; I'd rather that working tree live in some branch - which could still remain accessible (git module paths style)

**Comment by james-darkfox** [comment]
Anyhow. Happy hacking. o/

**Comment by zancarius** [comment]
Possibly true, but this is an assortment of PKGBUILDs. It doesn't *really* matter, and since I'm the only one who bothers with it, fussing over the structure is akin to splitting hairs--what's the point?

Besides, all AUR4 packages are now themselves handled by Git on the Arch side of things, so aside from having a singular area I can stuff all of my work (along with issue tracking, etc.), one could reasonably argue there's no reason for this repository to exist either. And once they support branches in the aur code (or issue tracking themselves), I *might* even be so inclined as to remove this entirely. No point duplicating effort.

Incidentally:

```
[gridlock:oh-my-zsh]$ cat .git/config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        fetch = +refs/heads/*:refs/remotes/origin/*
        url = https://github.com/archeydevil/oh-my-zsh.git
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

It appears in my PKGBUILD directory that I still have your original repository.

Oh, that's right. Work-in-progress intermediate build directories (`pkg`, `src`) that I have added to my `.gitignore` file might be the reason why I didn't want to bother with removing some of these outright (or moving them to another branch). One, I didn't want to pollute my repository with them, and two, I probably didn't want to delete them either.

**Comment by james-darkfox** [comment]
I just found out about AUR4 earlier, does it seem like it works well?

(I jumped ship when btrfs crashed my last arch install; not returning because of systemd - among other reasons. Gentoo :+1: )

**Comment by james-darkfox** [comment]
Also; in regard to the original repo. You could upload to your GH if you would like (considering you don't use it yourself... You might as well just have fun with a good cleanup on your system). ;-)

**Comment by zancarius** [comment]
Former Gentoo user here, oddly enough. Actually, before that it was OpenBSD -> FreeBSD -> Gentoo then finally Arch. (I use/have used Ubuntu for some purposes, but I'm not much of a fan of Debian-based distros--nothing against them, they work well, I just don't like them.) 

I mostly dumped Gentoo because of the fun that was re-compiling glibc, xorg, KDE, etc., and I never *really* trusted pre-built binary packages since sometimes the repositories would either disappear or there'd be weird breakage--and finding a good overlay was, on occasion, painful. But that experience goes back some time ago (I migrated to Arch around 2011-2012). I still have a couple Gentoo VMs running to keep myself dabbling in it from time to time, and some of the recent changes have been quite nice, but nothing exceptional. Even my home router/fileserver box runs Arch, but that's mostly because I'm *really* lazy and prefer some homogeneity among my systems where appropriate or possible. Though it persisted as a Gentoo install well into 2013, IIRC.

While I'm in the mood for embarrassing (or maybe not so embarrassing) confessions: If I were to ever dump Arch, I'd go back to Gentoo before anything else. I have fond memories of Gentoo. It was my first Linux distribution and the one I think is most similar to the *BSDs in its philosophy and design.

AUR4 is a nice change, and it's why there's a lingering sense in my mind that Github PKGBUILD repos may eventually go the way of the dodo. Updates are just a `git push`, but you have to do some magic with `mksrcinfo` so their pre-commit-hook parsers, AUR front end, and undoubtedly other machinery can know what to do with the changes (as I understand it, that's mostly limited to versioning and other things the AUR software likes). I saw on the mailing list some time back that there's ongoing discussion regarding branches. I don't know what will come of it or if it's already in the works, but I have a very strong suspicion that branching will be added. If that's the case, other features are almost assured.

Already, due to the migration, my local copy of this repo has gotten somewhat messier in layout (not so much function) since each PKGBUILD must be its own repository. I'm reluctant to do anything else with it (submodules, etc.) mostly due to the lack of AUR4-supported branches, but it's a work in progress, and I'm happy with what they've done. It's now possible to have co-maintainers on the AUR side and split packages are becoming much easier to deal with. Some of the slightly painful, repetitive nonsense has been cleaned up or removed, so that's another plus.

As far as your old repository goes, I doubt I'll do much with it. I'm an archivist at heart (such a confession, I'm aware, might lend some insight into my motives with this repo in particular), so I may keep it--it weighs in under 1MiB, so what's the point in deleting it?--but that's little guarantee for what may become of it. Besides, most of my time spent writing code is spent on a half dozen other things (not hosted here, thank you GitLab!), so my motivations, energy, and time wouldn't be of much use--and my experience with shell-related code (any of them) is admittedly rather limited.

I greatly appreciate the work you put into your own omz fork. "Arch-ificating" it made it much more useful to me, especially when I first started migrating from bash to zsh, and if you continued maintaining it, I would've remained a faithful user. As it stands, though, the `oh-my-zsh-git` PKGBUILD does well enough for me, provided I disable some of the more... obnoxious plugins.

If you have an interest in your old repo, I've temporarily put it [here](http://aries.destrealm.org/bshelton/oh-my-zsh.tar.gz) (I'll remove that link in a few days).

Anyway, it's well passed my bedtime here in the 'States. It's been fun.

Cheers, mate.

**Comment by james-darkfox** [comment]
^ Slowly reading this. You might as well write more blog posts. ;-)

**Comment by james-darkfox** [comment]
It is nice to know that my code does get used and appreciated. The main goal that I remember for my interest with OMZ was simply to keep everything simple - which eventually lead me to leaving it as it was by nature - not a simple thing. :-P

Thanks for the archive. I'll take a skim through my old code. :-)

**Comment by james-darkfox** [comment]
As for AUR4: Nice to hear about the branches, I've been contemplating a similar structure to improve or replace https://crates.io/ (rust dependency manager).

I first went to Arch due to how it was very BSD-like while being a very simple Linux distribution that just did what you wanted it to. With the SystemD move and other specifics it has made it less desirable while Gentoo remains true to my initial rational for why I started with Arch.

I should probably note that I'm running my Gentoo from the livecd on an overly underspec'd laptop and am yet to complete the install... Overly underspec'd = single core atom, 2g ram, serpent256-sha512 (no hardware acceleration) luks encrypted 64G (in which I use ~4G) micro-sd card. Doesn't take too long to update my tools. But I also don't have xorg, and friends yet. Gentoo as a development environment - PERFECT.

I - unlike you - intend to configure my Gentoo install to be as minimal as suitable for a personalized development environment. Here this environment will become a catalyst configuration and everything will be ephemeral (no archives!). Likely just boot the base system from the sd card directly into ram. Reference the SD for respective files and state/snapshots for overlays/updates. Here that would generally not over-write to the SD card. Expecting good performance from this environment considering my underspec'd hardware.

My main computer is a freebsd laptop - equally spec'd but with a 160G HDD.

Something that people who have read my shell scripts (and often other code too) would know - I really over compact things sometimes. Haskell was also great for this with fairly complicated one-liners.

Rust is my new language of choice and I must say, I'm loving it and would recommend that you take a look. I even have a couple of crates on my GH and a fairly large project kept privately for now too. :-)

Feel free to contact me on IRC, think it owuld be a better location for our chat ^^^ `/msg memoserv send darkfox hello` (memoserv because personal whitelist for contacts).

**I'll be deleting my messages when you respond to this - and would appreciate it if you would do the same (just up to where the issue is closed).**

**Comment by zancarius** [comment]
Any particular reason why you have an affinity for suggesting I delete my responses as well?

**Comment by james-darkfox** [comment]
Off-topic for the issue. Also, doesn't hurt to maintain privacy - especially considering how open this medium is.

**Comment by zancarius** [comment]
I'm not especially concerned. Nothing I've written is particularly secretive, informational, or insightful. Boring, perhaps, is a better qualifier.

You're welcome to your own choices, of course, as I see you have.

Cheers.
